### ISSUE TITLE
Investigate template rendering

### ISSUE THREAD

**Issue by perry-** [kidsakoder/kidsakoder-no-app#4]
Enonic XP uses Thymeleaf out of the box, investigate pros/cons of switching rendering language

**Comment by SolveH** [comment]
We think that since it is used in Enonic XP, and after the tutorial we had it seemed like Thymeleaf is all right to use, and that there's a lot of documentation out there to help us. We saw that Mustache and Xslt was mentioned in the docs http://xp.readthedocs.io/en/stable/developer/views.html?highlight=xslt . Thymeleaf seems to be more integrated with Enonic XP, but the technologies seems pretty similar.

**Comment by perry-** [comment]
Yeah, Thymeleaf is probably the best option. XSLT is the "old way" of doing templates in Enonic, and Mustache is probably less documented.

**Comment by siddise** [comment]
The choice was to use the out of the box Thymeleaf
